[theme]
primaryColor = "#3ddc97"
backgroundColor = "#14161b"
secondaryBackgroundColor = "#1c1f26"
textColor = "#e4e6eb"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
